const SET_SUBCATEGORY = 'SET_SUBCATEGORY';
const SET_SUBCATEGORIES = 'SET_SUBCATEGORIES';
const GET_SUBCATEGORIES = 'GET_SUBCATEGORIES';
const SET_LOADING = 'SET_LOADING';

export {
    SET_SUBCATEGORY,
    SET_SUBCATEGORIES,
    GET_SUBCATEGORIES,
    SET_LOADING,
}
