const SET_PRODUCT = 'SET_PRODUCT';
const SET_PRODUCTS = 'SET_PRODUCTS';
const GET_PRODUCTS = 'GET_PRODUCTS';
const SET_LOADING = 'SET_LOADING';

export {
    SET_PRODUCT,
    SET_PRODUCTS,
    GET_PRODUCTS,
    SET_LOADING,
}
