const SET_PRODUCT = 'SET_PRODUCT';
const SET_PRODUCTS = 'SET_PRODUCTS';
const GET_PRODUCTS = 'GET_PRODUCTS';
const GET_SEARCHED_PRODUCTS = 'GET_SEARCHED_PRODUCTS';
const SET_SEARCHED_PRODUCTS = 'SET_SEARCHED_PRODUCTS';
const GET_PRODUCT_BY_ID = 'GET_PRODUCT_BY_ID';
const SET_PRODUCTS_PAGINATION = 'SET_PRODUCTS_PAGINATION';
const SET_LOADING = 'SET_LOADING';
const SET_SEARCH_LOADING = 'SET_SEARCH_LOADING';

export {
  SET_PRODUCT,
  SET_PRODUCTS,
  GET_PRODUCTS,
  SET_PRODUCTS_PAGINATION,
  GET_PRODUCT_BY_ID,
  GET_SEARCHED_PRODUCTS,
  SET_SEARCHED_PRODUCTS,
  SET_LOADING,
  SET_SEARCH_LOADING
};
