const SET_CATEGORY = 'SET_CATEGORY';
const SET_CATEGORIES = 'SET_CATEGORIES';
const GET_CATEGORIES = 'GET_CATEGORIES';
const SET_LOADING = 'SET_LOADING';

export {
    SET_CATEGORY,
    SET_CATEGORIES,
    GET_CATEGORIES,
    SET_LOADING,
}
