const GET_NOVAPOSHTA_CITIES = 'GET_NOVAPOSHTA_CITIES';
const SET_NOVAPOSHTA_CITIES = 'SET_NOVAPOSHTA_CITIES';
const GET_NOVAPOSHTA_WAREHOUSES = 'GET_NOVAPOSHTA_WAREHOUSES';
const SET_NOVAPOSHTA_WAREHOUSES = 'SET_NOVAPOSHTA_WAREHOUSES';
const GET_NOVAPOSHTA_STREETS = 'GET_NOVAPOSHTA_STREETS';
const SET_NOVAPOSHTA_STREETS = 'SET_NOVAPOSHTA_STREETS';
const GET_NOVAPOSHTA_DELIVERY_PRICE = 'GET_NOVAPOSHTA_DELIVERY_PRICE';
const SET_NOVAPOSHTA_DELIVERY_PRICE = 'SET_NOVAPOSHTA_DELIVERY_PRICE';
const SET_LOADING = 'SET_LOADING';

export {
  GET_NOVAPOSHTA_CITIES,
  SET_NOVAPOSHTA_CITIES,
  SET_NOVAPOSHTA_WAREHOUSES,
  GET_NOVAPOSHTA_WAREHOUSES,
  GET_NOVAPOSHTA_STREETS,
  SET_NOVAPOSHTA_STREETS,
  GET_NOVAPOSHTA_DELIVERY_PRICE,
  SET_NOVAPOSHTA_DELIVERY_PRICE,
  SET_LOADING
};
